[package]
name = "orion-fuzz"
version = "0.1.0"
authors = ["brycx <brycx@protonmail.com>"]

[dependencies]
honggfuzz = "0.5.45"
rand_chacha = "0.2.1"
rand_core = "0.5.0"
sodiumoxide = "0.2.2"
ring = "0.16.5"
blake2-rfc = "0.2.18"
chacha = "0.3.0"
orion = { path = "../orion/" }

[[bin]]
name = "high_level_api"
path = "src/high_level_api.rs"

[[bin]]
name = "aead"
path = "src/aead.rs"

[[bin]]
name = "hash"
path = "src/hash.rs"

[[bin]]
name = "mac"
path = "src/mac.rs"

[[bin]]
name = "stream"
path = "src/stream.rs"

[[bin]]
name = "newtypes"
path = "src/newtypes.rs"

[[bin]]
name = "kdf"
path = "src/kdf.rs"

[[bin]]
name = "secret_stream"
path = "src/secret_stream.rs"

[profile.release]
opt-level = 3