[package]
name = "orion-fuzz"
version = "0.1.0"
authors = ["brycx <brycx@protonmail.com>"]
edition = "2018"

[dependencies]
honggfuzz = "0.5.45"
rand = "0.7.3"
rand_chacha = "0.2.1"
sodiumoxide = "0.2.5"
ring = "0.16.9"
blake2-rfc = "0.2.18"
chacha = "0.3.0"
orion = { git = "https://github.com/brycx/orion", branch = "argon" }
rust-argon2 = "0.7.0"

[[bin]]
name = "high_level_api"
path = "src/high_level_api.rs"

[[bin]]
name = "aead"
path = "src/aead.rs"

[[bin]]
name = "hash"
path = "src/hash.rs"

[[bin]]
name = "mac"
path = "src/mac.rs"

[[bin]]
name = "stream"
path = "src/stream.rs"

[[bin]]
name = "newtypes"
path = "src/newtypes.rs"

[[bin]]
name = "kdf"
path = "src/kdf.rs"

[[bin]]
name = "aead_stream"
path = "src/aead_stream.rs"

[profile.release]
opt-level = 3